fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    inifile: https://github.com/puppetlabs/puppetlabs-inifile.git
    grafana:
      repo: https://github.com/voxpupuli/puppet-grafana.git
      ref: v7.0.0
    yumrepo:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    telegraf:
      repo: https://github.com/voxpupuli/puppet-telegraf.git
      ref: v3.1.0
    facts: https://github.com/puppetlabs/puppetlabs-facts.git
    puppet_agent: https://github.com/puppetlabs/puppetlabs-puppet_agent.git
    provision: https://github.com/puppetlabs/provision.git
    puppet_metrics_collector: https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector.git
