fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    inifile: https://github.com/puppetlabs/puppetlabs-inifile.git
    grafana: https://github.com/voxpupuli/puppet-grafana.git
    yumrepo:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    telegraf:
      repo: https://github.com/voxpupuli/puppet-telegraf.git
    facts: https://github.com/puppetlabs/puppetlabs-facts.git
    puppet_agent: https://github.com/puppetlabs/puppetlabs-puppet_agent.git
    provision: https://github.com/puppetlabs/provision.git
    puppet_metrics_collector: https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector.git
    puppet_conf: "https://github.com/puppetlabs/puppetlabs-puppet_conf"
    deploy_pe: 'git://github.com/jarretlavallee/puppet-deploy_pe.git'
    ruby_task_helper: "https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper"
    cron_core: "git://github.com/puppetlabs/puppetlabs-cron_core"
    bootstrap: "https://github.com/puppetlabs/puppetlabs-bootstrap"
