---
common:

".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
  required:
    ':development':
      - gem: 'toml-rb'
      - gem: 'octokit'
        version:
          '= 4.21.0'
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: true
.gitpod.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.travis.yml:
  delete: true
Rakefile:
  changelog_user: "puppetlabs"
.rubocop.yml:
  default_configs: 
    "RSpec/EmptyExampleGroup": 
       Enabled: False
